services:
  graph:
    image: neo4j:2025.11.2
    restart: always
    ports:
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/your_password
    volumes:
      - horizon-graph:/data


volumes:
  horizon-graph: